/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginform;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author monster
 */
public class personelanasayfa extends javax.swing.JFrame {
    private static final String DB_URL = "jdbc:mysql://localhost:1234/kutuphaneyonetim";
    private static final String USER = "root";
    private static final String PASSWORD = "12345";
    private KitapIslemleri kitapIslemleri;
    
    /**
     * Creates new form personelanasayfa
     */
    public personelanasayfa() {
        initComponents();
            Connection connection = DatabaseConnection.getInstance().getConnection();
            kitapIslemleri = new KitapIslemleri(connection);
        
        showBooksInTable(jTable1, "SELECT * FROM kitaplar");
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedRow = jTable1.getSelectedRow();

                // Check if a row is selected
                if (selectedRow != -1) {
                    // Get values from the selected row
                    String isbn = jTable1.getValueAt(selectedRow, 0).toString();
                    String kitapAdi = jTable1.getValueAt(selectedRow, 1).toString();
                    String yazar = jTable1.getValueAt(selectedRow, 2).toString();
                    String durum = jTable1.getValueAt(selectedRow, 3).toString();

                    // Set values to the text fields
                    txtpersonelkitapeklesilgüncelleısbn.setText(isbn);
                    txtpersonelkitapeklesilgüncellekitapadı.setText(kitapAdi);
                    txtpersonelkitapeklesilgüncelleryazar.setText(yazar);
                    txtpersonelkitapeklesilgüncelledurum.setText(durum);
                    
                }
            }
        });

        showBooksInTable(jTable1, "SELECT * FROM kitaplar");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnpersonelanasayfakitabısilin = new javax.swing.JButton();
        personelkitapekleısbn = new javax.swing.JLabel();
        txtpersonelkitapeklesilgüncelleısbn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpersonelkitapeklesilgüncelledurum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpersonelkitapeklesilgüncellekitapadı = new javax.swing.JTextField();
        txtpersonelkitapeklesilgüncelleryazar = new javax.swing.JTextField();
        btnpersonelkitapekle = new javax.swing.JButton();
        btnpersonelAnasayfaKıtaplar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnpersonelanasayfacikisyap = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profil.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        btnpersonelanasayfakitabısilin.setBackground(new java.awt.Color(185, 137, 137));
        btnpersonelanasayfakitabısilin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnpersonelanasayfakitabısilin.setForeground(new java.awt.Color(204, 0, 0));
        btnpersonelanasayfakitabısilin.setText("KİTABI SİL");
        btnpersonelanasayfakitabısilin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonelanasayfakitabısilinActionPerformed(evt);
            }
        });

        personelkitapekleısbn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        personelkitapekleısbn.setForeground(new java.awt.Color(0, 102, 102));
        personelkitapekleısbn.setText("ISBN :");

        txtpersonelkitapeklesilgüncelleısbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonelkitapeklesilgüncelleısbnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("DURUM :");

        txtpersonelkitapeklesilgüncelledurum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonelkitapeklesilgüncelledurumActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("YAZAR :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("KİTAP ADI :");

        txtpersonelkitapeklesilgüncellekitapadı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonelkitapeklesilgüncellekitapadıActionPerformed(evt);
            }
        });

        txtpersonelkitapeklesilgüncelleryazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonelkitapeklesilgüncelleryazarActionPerformed(evt);
            }
        });

        btnpersonelkitapekle.setBackground(new java.awt.Color(51, 153, 255));
        btnpersonelkitapekle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnpersonelkitapekle.setForeground(new java.awt.Color(0, 102, 102));
        btnpersonelkitapekle.setText("KİTAP EKLE");
        btnpersonelkitapekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonelkitapekleActionPerformed(evt);
            }
        });

        btnpersonelAnasayfaKıtaplar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnpersonelAnasayfaKıtaplar.setForeground(new java.awt.Color(0, 102, 102));
        btnpersonelAnasayfaKıtaplar.setText("KİTAPLAR");
        btnpersonelAnasayfaKıtaplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonelAnasayfaKıtaplarActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(0, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "KİTAP ADI", "YAZAR", "DURUM"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnpersonelanasayfacikisyap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnpersonelanasayfacikisyap.setForeground(new java.awt.Color(255, 0, 0));
        btnpersonelanasayfacikisyap.setText("ÇIKIŞ YAP");
        btnpersonelanasayfacikisyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonelanasayfacikisyapActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("KİTABI GÜNCELLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 905, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnpersonelanasayfacikisyap, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(353, 353, 353))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personelkitapekleısbn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpersonelkitapeklesilgüncelleısbn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpersonelkitapeklesilgüncelledurum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(48, 48, 48)
                                .addComponent(txtpersonelkitapeklesilgüncelleryazar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtpersonelkitapeklesilgüncellekitapadı, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnpersonelanasayfakitabısilin, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpersonelkitapekle, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpersonelAnasayfaKıtaplar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpersonelkitapeklesilgüncellekitapadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personelkitapekleısbn)
                            .addComponent(jLabel8)
                            .addComponent(txtpersonelkitapeklesilgüncelleısbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(txtpersonelkitapeklesilgüncelleryazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpersonelkitapeklesilgüncelledurum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnpersonelanasayfakitabısilin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnpersonelkitapekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnpersonelAnasayfaKıtaplar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnpersonelanasayfacikisyap, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 960, 630));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iadeet.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 430));

        setSize(new java.awt.Dimension(1257, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpersonelanasayfacikisyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonelanasayfacikisyapActionPerformed
        login logn = new login();
        logn.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnpersonelanasayfacikisyapActionPerformed

    private void btnpersonelAnasayfaKıtaplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonelAnasayfaKıtaplarActionPerformed
      
    }//GEN-LAST:event_btnpersonelAnasayfaKıtaplarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked
    
    private void btnpersonelanasayfakitabısilinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonelanasayfakitabısilinActionPerformed
         String isbnToDelete = txtpersonelkitapeklesilgüncelleısbn.getText();

// Check if the ISBN is provided
if (isbnToDelete.isEmpty()) {
    JOptionPane.showMessageDialog(this, "ISBN boş olamaz.");
    return;
}

// Confirmation dialog before deleting
int dialogResult = JOptionPane.showConfirmDialog(this, isbnToDelete + " ISBN numaralı kitabı silmek istediğinize emin misiniz?", "Bilgilendirme", JOptionPane.YES_NO_OPTION);

if (dialogResult == JOptionPane.YES_OPTION) {
    

    // Kitabı sil
    kitapIslemleri.kitapSil(isbnToDelete);

    // Tabloyu güncelle
    showBooksInTable(jTable1, "SELECT * FROM kitaplar");

    // Text alanlarını temizle
    txtpersonelkitapeklesilgüncellekitapadı.setText("");
    txtpersonelkitapeklesilgüncelleryazar.setText("");
    txtpersonelkitapeklesilgüncelledurum.setText("");
    txtpersonelkitapeklesilgüncelleısbn.setText("");
}
    }//GEN-LAST:event_btnpersonelanasayfakitabısilinActionPerformed

    private void txtpersonelkitapeklesilgüncelleısbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonelkitapeklesilgüncelleısbnActionPerformed
        // TODO add your handling code here:
         String isbnToDelete = txtpersonelkitapeklesilgüncelleısbn.getText();

   
    if (isbnToDelete.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ISBN bos olamaz.");
        return;
    }

    
    int dialogResult = JOptionPane.showConfirmDialog(this,  isbnToDelete + " ISBN numaralı kitabı silmek istediginize emin misiniz?", "Bilgilendirme", JOptionPane.YES_NO_OPTION);
    if (dialogResult == JOptionPane.YES_OPTION) {
        
        deleteBook(isbnToDelete);

        
        showBooksInTable(jTable1, "SELECT * FROM kitaplar");

        
       txtpersonelkitapeklesilgüncellekitapadı.setText("");
        txtpersonelkitapeklesilgüncelleryazar.setText("");
        txtpersonelkitapeklesilgüncelledurum.setText("");
        txtpersonelkitapeklesilgüncelleısbn.setText("");
    }
}

private void deleteBook(String isbnToDelete) {
    String query = "DELETE FROM kitaplar WHERE ISBN = ?";

    try (Connection connection = DriverManager.getConnection(DB_URL, USER, PASSWORD);
         PreparedStatement preparedStatement = connection.prepareStatement(query)) {

        
        preparedStatement.setString(1, isbnToDelete);

        
        int rowsAffected = preparedStatement.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, isbnToDelete + " ISBN numaralı kitap başarıyla silindi.");
        } else {
            JOptionPane.showMessageDialog(this, isbnToDelete + " ISBN numaralı kitap bulunamadı.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Kitap silinirken hata oluştu: " + e.getMessage());
    }
    }//GEN-LAST:event_txtpersonelkitapeklesilgüncelleısbnActionPerformed

    private void txtpersonelkitapeklesilgüncellekitapadıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonelkitapeklesilgüncellekitapadıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonelkitapeklesilgüncellekitapadıActionPerformed

    private void txtpersonelkitapeklesilgüncelleryazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonelkitapeklesilgüncelleryazarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonelkitapeklesilgüncelleryazarActionPerformed

    private void txtpersonelkitapeklesilgüncelledurumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonelkitapeklesilgüncelledurumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonelkitapeklesilgüncelledurumActionPerformed

    private void btnpersonelkitapekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonelkitapekleActionPerformed
     String kitapAdi= txtpersonelkitapeklesilgüncellekitapadı.getText();
     String yazar= txtpersonelkitapeklesilgüncelleryazar.getText();
     String durum= txtpersonelkitapeklesilgüncelledurum.getText();
     String isbn= txtpersonelkitapeklesilgüncelleısbn.getText();
        kitapIslemleri.kitapEkle(isbn, kitapAdi, yazar, durum);
    
    if (isbn.isEmpty() || kitapAdi.isEmpty() || yazar.isEmpty() || durum.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tum alanları doldurun.");
        return;
    }

   
    
    
    showBooksInTable(jTable1, "SELECT * FROM kitaplar");

   
        txtpersonelkitapeklesilgüncellekitapadı.setText("");
        txtpersonelkitapeklesilgüncelleryazar.setText("");
        txtpersonelkitapeklesilgüncelledurum.setText("");
        txtpersonelkitapeklesilgüncelleısbn.setText("");
    }//GEN-LAST:event_btnpersonelkitapekleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String yenikitapAdi = txtpersonelkitapeklesilgüncellekitapadı.getText();
String yeniyazar = txtpersonelkitapeklesilgüncelleryazar.getText();
String yenidurum = txtpersonelkitapeklesilgüncelledurum.getText();
String yeniisbn = txtpersonelkitapeklesilgüncelleısbn.getText();


if (yeniisbn.isEmpty() || yenikitapAdi.isEmpty() || yeniyazar.isEmpty() || yenidurum.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Tüm alanları doldurun.");
    return;
}




kitapIslemleri.kitapGuncelle(yeniisbn, yenikitapAdi, yeniyazar, yenidurum);


showBooksInTable(jTable1, "SELECT * FROM kitaplar");


txtpersonelkitapeklesilgüncellekitapadı.setText("");
txtpersonelkitapeklesilgüncelleryazar.setText("");
txtpersonelkitapeklesilgüncelledurum.setText("");
txtpersonelkitapeklesilgüncelleısbn.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
private void showBooksInTable(javax.swing.JTable table, String query, String... params) {
    try {
        Connection connection = DriverManager.getConnection(DB_URL, USER, PASSWORD);
        PreparedStatement preparedStatement = connection.prepareStatement(query);

        
        for (int i = 0; i < params.length; i++) {
            preparedStatement.setString(i + 1, params[i]);
        }

        ResultSet resultSet = preparedStatement.executeQuery();

        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

       
        while (resultSet.next()) {
            String kitapAdi = resultSet.getString("kitapAdi");
            String yazar = resultSet.getString("yazar");
            String isbn = resultSet.getString("ISBN");
            
            String durum = resultSet.getString("durum");

            Object[] row = {isbn, kitapAdi, yazar, durum};
            model.addRow(row);
        }

        resultSet.close();
        preparedStatement.close();
        connection.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personelanasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personelanasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personelanasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personelanasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personelanasayfa().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpersonelAnasayfaKıtaplar;
    private javax.swing.JButton btnpersonelanasayfacikisyap;
    private javax.swing.JButton btnpersonelanasayfakitabısilin;
    private javax.swing.JButton btnpersonelkitapekle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel personelkitapekleısbn;
    private javax.swing.JTextField txtpersonelkitapeklesilgüncelledurum;
    private javax.swing.JTextField txtpersonelkitapeklesilgüncellekitapadı;
    private javax.swing.JTextField txtpersonelkitapeklesilgüncelleryazar;
    private javax.swing.JTextField txtpersonelkitapeklesilgüncelleısbn;
    // End of variables declaration//GEN-END:variables
}
